spring.application.name=backendreilief

spring.datasource.url=jdbc:mysql://shortline.proxy.rlwy.net:56760/railway?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=wYqxbPstgQRMOLBaUicKytbbhujEvwjd

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect


server.port=${PORT:8081}