spring.datasource.url=jdbc:mysql://shortline.proxy.rlwy.net:56760/railway?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&autoReconnect=true

spring.datasource.username=root
spring.datasource.password=wYqxbPstgQRMOLBaUiCkytbbhujEvwjd

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true